runtime: python27
api_version: 1
threadsafe: true
service: coinsafe

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: public/\1
  upload: public/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: public/\1
  upload: public/(.*\.js)

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: public/\1
  upload: public/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /(.*\.(svg|svgz))
  mime_type: image/svg+xml
  static_files: public/\1
  upload: public/(.*\.(svg|svgz))

- url: /(.+)/
  static_files: public/\1/index.html
  upload: public/(.*)/index.html

- url: /(.+)
  static_files: public/\1/index.html
  upload: public/(.*)/index.html

- url: /
  static_files: public/index.html
  upload: public/index.html
